[variables]
NODE_VERSION = "20"

[phases.install]
cmds = [
  "npm install --prefix frontend",
  "npm install --prefix backend"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate"
]

[start]
cmd = "node start.js"
