-- AlterTable
ALTER TABLE "Note" ADD COLUMN "startAt" DATETIME;
ALTER TABLE "Note" ADD COLUMN "endAt" DATETIME;
ALTER TABLE "Note" ADD COLUMN "allDay" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "Note" ADD COLUMN "color" TEXT NOT NULL DEFAULT 'blue';
